export const bridgeFormLabels = {
  region: 'Region',
  bridgeName: 'Bridge name',
  coordinates: 'Coordinates',
  roadOrHighway: 'Road or Highway',
  motBridgeId: 'MOT Bridge ID',
  bridgeType: 'Bridge type',
  spanMaterial: 'Span material',
  abutmentOrBackWall: 'Abutment or back wall',
  underdeck: 'Underdeck',
  beams: 'Beams',
  columns: 'Columns',
  heightFromBeamsOrDeckToSurfaceBelow:
    'Height from beams or deck to surface below',
  length: 'Length from MOTI or estimate',
  bridgeIfFor: 'Bridge if for',
  crossingType: 'Crossing type',
  waterCurrentlyUnderBridge: 'Water currently under bridge',
  waterIs: 'Water is',
  habitatAroundBridge: 'Habitat around bridge',
  habitatComments: 'Habitat comments',
};
